### ISSUE TITLE
Build ideep with installed mkl-dnn?

### ISSUE THREAD

**Issue by jiapei100** [intel/ideep#20]
Hi, I just wonder if I can build ideep with an already-installed mkl-dnn?
Currently, I've been obtaining the following error message if I `didn't git clone --recursive` ?

> CMake Error at cmake/mkldnn.cmake:16 (add_subdirectory):
>    The source directory
> 
>     ....../ideep/mkl-dnn
> 
>    does not contain a CMakeLists.txt file.
>  Call Stack (most recent call first):
>    CMakeLists.txt:13 (include)

I prefer building ideep with the newest mkl-dnn which has already been installed?

Cheerrs
Pei

**Comment by mingxiaoh** [comment]
The process to build Chainer Backend for Intel Architecture is:
git submodule update --init
mkdir build && cd build && cmake .. & cd ../python
python setup.py install

If you doesn't execute "git submodule update --init", Cmake will be error since it need to build mkl-dnn. If you want to build a newest mkl-dnn, you can try as below:
git submodule update --init
cd mkl-dnn
git checkout master && git pull && cd ../
mkdir build && cd build && cmake .. & cd ../python
python setup.py install

**Comment by 4pao** [comment]
Do you use python part? @jiapei100

**Comment by mingxiaoh** [comment]
If you don't use python part, try as below:
git submodule update --init
cd mkl-dnn && git checkout master && git pull && cd ../ (in this step, you checkout the latest mkl-dnn)
mkdir build && cd build && cmake .. & make -j
